package com.joker.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoles<M extends BaseRoles<M>> extends Model<M> implements IBean {

	public void setRoleId(Long roleId) {
		set("role_id", roleId);
	}

	public Long getRoleId() {
		return get("role_id");
	}

	public void setRoleName(String roleName) {
		set("role_name", roleName);
	}

	public String getRoleName() {
		return get("role_name");
	}

	public void setRoleDesc(String roleDesc) {
		set("role_desc", roleDesc);
	}

	public String getRoleDesc() {
		return get("role_desc");
	}

	public void setEnabled(Integer enabled) {
		set("enabled", enabled);
	}

	public Integer getEnabled() {
		return get("enabled");
	}

}
