package com.joker.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.joker.common.model.base.BaseResources;
import org.apache.commons.lang3.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resources extends BaseResources<Resources> {
    public static final Resources dao = new Resources();

    public Page<Resources> paginate(int pageNumber, int pageSize, String searchData) {
        if (!StringUtils.isBlank(searchData)) {
            searchData='%'+searchData+'%';
            return paginate(pageNumber, pageSize, "select *", "from resources where resource_string like ? order by resource_id asc", searchData);
        } else {
            return paginate(pageNumber, pageSize, "select *", "from resources where 1=1 order by resource_id asc");
        }
    }
}
