package com.joker.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.joker.common.model.base.BaseResources;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resources extends BaseResources<Resources> {
    public static final Resources dao = new Resources();

    public Page<Resources> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from resources order by resource_id asc");
    }
}
