package com.joker.common.model;

import com.joker.common.model.base.BaseRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roles extends BaseRoles<Roles> {
	public static final Roles dao = new Roles();
}
