package com.joker.common.model;

import com.joker.common.model.base.BaseRolesResources;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolesResources extends BaseRolesResources<RolesResources> {
	public static final RolesResources dao = new RolesResources();
}
