package com.joker.common.model;

import com.joker.common.model.base.BaseUsersRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersRoles extends BaseUsersRoles<UsersRoles> {
	public static final UsersRoles dao = new UsersRoles();
}
